schema-version = 1

[package]
title = "Astra"
version = "1.0.2"
id = "com.astra.tv"
icon = "@image/icon_512x512.png"

[components]
[[components.interactive]]
id = "com.astra.tv.main"
runtime-module = "/com.amazon.kepler.keplerscript.runtime.loader_2@IKeplerScript_2_0"
launch-type = "singleton"
categories = ["com.amazon.category.main", "com.amazon.category.kepler.media"]

[[wants.service]]
id = "com.amazon.w3cmedia.service"

[[wants.service]]
id = "com.amazon.audio.service"

[[wants.service]]
id = "com.amazon.inputmethod.service"

[[wants.service]]
id = "com.amazon.inputd.service"

[[wants.service]]
id = "com.amazon.media.server"

[[wants.service]]
id = "com.amazon.mediametrics.service"

[[wants.service]]
id = "com.amazon.media.playersession.service"

[[wants.service]]
id = "com.amazon.mediabuffer.service"

[[wants.service]]
id = "com.amazon.mediatransform.service"

[[wants.service]]
id = "com.amazon.gipc.uuid.*"

[[wants.service]]
id = "com.amazon.audio.stream"

[[wants.service]]
id = "com.amazon.audio.control"

[[wants.service]]
id = "com.amazon.audio.system"

[[wants.service]]
id = "com.amazon.network.service"

[[needs.privilege]]
id = "com.amazon.network.privilege.net-info"

[[extras]]
key = "interface.provider"
component-id = "com.astra.tv.main"

[extras.value.application]
[[extras.value.application.interface]]
interface_name = "com.amazon.kepler.media.IMediaPlaybackServer"
command_options = [
    "StartOver",
    "SkipForward",
    "SkipBackward",
]
attribute_options = ["AudioAdvanceMuted"]
features = ["AdvancedSeek", "VariableSpeed", "AudioTracks", "TextTracks"]
